[package]
name = "draft"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    ".",
    "crates/draft_render",
    "crates/draft_app",
    "crates/draft_internal",
    "crates/draft_window",
    "crates/draft_winit",
]

[workspace.dependencies]
fyrox-resource = { git = "https://github.com/zuiyu1998/Fyrox.git" }
fyrox-core = { git = "https://github.com/zuiyu1998/Fyrox.git" }
frame-graph = { git = "https://github.com/zuiyu1998/frame-graph.git" }

log = { version = "0.4", default-features = false }
downcast-rs = { version = "2.0" }
variadics_please = "1.1"
thiserror = "2.0"

[dependencies]
draft_internal = { path = "./crates/draft_internal" }
