[package]
name = "draft"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "./crates/*"]

[workspace.dependencies]
fyrox-resource = { git = "https://github.com/zuiyu1998/Fyrox.git" }
frame-graph = { git = "https://github.com/zuiyu1998/frame-graph.git" }

[dependencies]