[package]
name = "draft"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "./crates/*", "crates/draft_window"]

[workspace.dependencies]
fyrox-resource = { git = "https://github.com/zuiyu1998/Fyrox.git" }
frame-graph = { git = "https://github.com/zuiyu1998/frame-graph.git" }

downcast-rs = { version = "2.0"}

[dependencies]
