[package]
name = "draft_render"
version = "0.1.0"
edition = "2024"

[dependencies]
draft_window = { path = "../draft_window" }
draft_graphics = { path = "../draft_graphics" }
draft_mesh = { path = "../draft_mesh" }
draft_material = { path = "../draft_material" }
draft_shader = { path = "../draft_shader" }

fyrox-resource = { workspace = true }
fyrox-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
fxhash = { workspace = true }
bitflags = { workspace = true }
tracing = { workspace = true }
encase = { workspace = true  }
nonmax = "0.5"
offset-allocator = "0.2"