[package]
name = "draft_render"
version = "0.1.0"
edition = "2024"

[dependencies]
draft_window = { path = "../draft_window" }

fyrox-resource = { workspace = true }
fyrox-core = { workspace = true }
frame-graph = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

serde_pretty_yaml = { version = "0.9" }
wgpu = { version = "27" }
futures-lite = { version = "2.6" }
bitflags = { version = "2.10" }
