[package]
name = "draft_render"
version = "0.1.0"
edition = "2024"

[dependencies]
draft_window = { path = "../draft_window" }
draft_graphics = { path = "../draft_graphics" }
draft_geometry = { path = "../draft_geometry" }

fyrox-resource = { workspace = true }
fyrox-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
fxhash = { workspace = true }

serde_pretty_yaml = { version = "0.9" }
wgpu = { version = "27" }
bitflags = { version = "2.10" }
