[package]
name = "draft_geometry"
version = "0.1.0"
edition = "2024"

[dependencies]
draft_graphics = { path = "../draft_graphics" }

fyrox-core = { workspace = true }
fyrox-resource = { workspace = true }
