[package]
name = "draft_graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
fyrox-core = { workspace = true }
serde = { workspace = true }
bitflags = { workspace = true }

wgpu = { version = "27", default-features = false, features = ["naga-ir"] }
