[package]
name = "draft_app"
version = "0.1.0"
edition = "2024"

[dependencies]
draft_render = { path = "../draft_render" }
draft_window = { path = "../draft_window" }
draft_scene = { path = "../draft_scene" }

fyrox-core = { workspace = true }
fyrox-resource = { workspace = true }

downcast-rs = { workspace = true }
variadics_please = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true, default-features = false }
